// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fim.proto

package fim

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FimdConfig struct {
	NodeName             string               `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	PodName              string               `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	Pid                  []int32              `protobuf:"varint,3,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	Cid                  []string             `protobuf:"bytes,4,rep,name=cid,proto3" json:"cid,omitempty"`
	Subject              []*FimWatcherSubject `protobuf:"bytes,5,rep,name=subject,proto3" json:"subject,omitempty"`
	LogFormat            string               `protobuf:"bytes,6,opt,name=logFormat,proto3" json:"logFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FimdConfig) Reset()         { *m = FimdConfig{} }
func (m *FimdConfig) String() string { return proto.CompactTextString(m) }
func (*FimdConfig) ProtoMessage()    {}
func (*FimdConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_56e8d7c6580709f8, []int{0}
}
func (m *FimdConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimdConfig.Unmarshal(m, b)
}
func (m *FimdConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimdConfig.Marshal(b, m, deterministic)
}
func (dst *FimdConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimdConfig.Merge(dst, src)
}
func (m *FimdConfig) XXX_Size() int {
	return xxx_messageInfo_FimdConfig.Size(m)
}
func (m *FimdConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FimdConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FimdConfig proto.InternalMessageInfo

func (m *FimdConfig) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *FimdConfig) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *FimdConfig) GetPid() []int32 {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *FimdConfig) GetCid() []string {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *FimdConfig) GetSubject() []*FimWatcherSubject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *FimdConfig) GetLogFormat() string {
	if m != nil {
		return m.LogFormat
	}
	return ""
}

type FimWatcherSubject struct {
	Path                 []string          `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Event                []string          `protobuf:"bytes,2,rep,name=event,proto3" json:"event,omitempty"`
	Ignore               []string          `protobuf:"bytes,3,rep,name=ignore,proto3" json:"ignore,omitempty"`
	OnlyDir              bool              `protobuf:"varint,4,opt,name=onlyDir,proto3" json:"onlyDir,omitempty"`
	Recursive            bool              `protobuf:"varint,5,opt,name=recursive,proto3" json:"recursive,omitempty"`
	MaxDepth             int32             `protobuf:"varint,6,opt,name=maxDepth,proto3" json:"maxDepth,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FimWatcherSubject) Reset()         { *m = FimWatcherSubject{} }
func (m *FimWatcherSubject) String() string { return proto.CompactTextString(m) }
func (*FimWatcherSubject) ProtoMessage()    {}
func (*FimWatcherSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_56e8d7c6580709f8, []int{1}
}
func (m *FimWatcherSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimWatcherSubject.Unmarshal(m, b)
}
func (m *FimWatcherSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimWatcherSubject.Marshal(b, m, deterministic)
}
func (dst *FimWatcherSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimWatcherSubject.Merge(dst, src)
}
func (m *FimWatcherSubject) XXX_Size() int {
	return xxx_messageInfo_FimWatcherSubject.Size(m)
}
func (m *FimWatcherSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_FimWatcherSubject.DiscardUnknown(m)
}

var xxx_messageInfo_FimWatcherSubject proto.InternalMessageInfo

func (m *FimWatcherSubject) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FimWatcherSubject) GetEvent() []string {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *FimWatcherSubject) GetIgnore() []string {
	if m != nil {
		return m.Ignore
	}
	return nil
}

func (m *FimWatcherSubject) GetOnlyDir() bool {
	if m != nil {
		return m.OnlyDir
	}
	return false
}

func (m *FimWatcherSubject) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *FimWatcherSubject) GetMaxDepth() int32 {
	if m != nil {
		return m.MaxDepth
	}
	return 0
}

func (m *FimWatcherSubject) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type FimdHandle struct {
	NodeName             string   `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	Pid                  []int32  `protobuf:"varint,3,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	ProcessEventfd       []int32  `protobuf:"varint,4,rep,packed,name=processEventfd,proto3" json:"processEventfd,omitempty"`
	MqFd                 int32    `protobuf:"varint,5,opt,name=mqFd,proto3" json:"mqFd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FimdHandle) Reset()         { *m = FimdHandle{} }
func (m *FimdHandle) String() string { return proto.CompactTextString(m) }
func (*FimdHandle) ProtoMessage()    {}
func (*FimdHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_56e8d7c6580709f8, []int{2}
}
func (m *FimdHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FimdHandle.Unmarshal(m, b)
}
func (m *FimdHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FimdHandle.Marshal(b, m, deterministic)
}
func (dst *FimdHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FimdHandle.Merge(dst, src)
}
func (m *FimdHandle) XXX_Size() int {
	return xxx_messageInfo_FimdHandle.Size(m)
}
func (m *FimdHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_FimdHandle.DiscardUnknown(m)
}

var xxx_messageInfo_FimdHandle proto.InternalMessageInfo

func (m *FimdHandle) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *FimdHandle) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *FimdHandle) GetPid() []int32 {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *FimdHandle) GetProcessEventfd() []int32 {
	if m != nil {
		return m.ProcessEventfd
	}
	return nil
}

func (m *FimdHandle) GetMqFd() int32 {
	if m != nil {
		return m.MqFd
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fim_56e8d7c6580709f8, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FimdConfig)(nil), "fim.FimdConfig")
	proto.RegisterType((*FimWatcherSubject)(nil), "fim.FimWatcherSubject")
	proto.RegisterMapType((map[string]string)(nil), "fim.FimWatcherSubject.TagsEntry")
	proto.RegisterType((*FimdHandle)(nil), "fim.FimdHandle")
	proto.RegisterType((*Empty)(nil), "fim.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FimdClient is the client API for Fimd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FimdClient interface {
	CreateWatch(ctx context.Context, in *FimdConfig, opts ...grpc.CallOption) (*FimdHandle, error)
	DestroyWatch(ctx context.Context, in *FimdConfig, opts ...grpc.CallOption) (*Empty, error)
	GetWatchState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Fimd_GetWatchStateClient, error)
}

type fimdClient struct {
	cc *grpc.ClientConn
}

func NewFimdClient(cc *grpc.ClientConn) FimdClient {
	return &fimdClient{cc}
}

func (c *fimdClient) CreateWatch(ctx context.Context, in *FimdConfig, opts ...grpc.CallOption) (*FimdHandle, error) {
	out := new(FimdHandle)
	err := c.cc.Invoke(ctx, "/fim.Fimd/CreateWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fimdClient) DestroyWatch(ctx context.Context, in *FimdConfig, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/fim.Fimd/DestroyWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fimdClient) GetWatchState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Fimd_GetWatchStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Fimd_serviceDesc.Streams[0], "/fim.Fimd/GetWatchState", opts...)
	if err != nil {
		return nil, err
	}
	x := &fimdGetWatchStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fimd_GetWatchStateClient interface {
	Recv() (*FimdHandle, error)
	grpc.ClientStream
}

type fimdGetWatchStateClient struct {
	grpc.ClientStream
}

func (x *fimdGetWatchStateClient) Recv() (*FimdHandle, error) {
	m := new(FimdHandle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FimdServer is the server API for Fimd service.
type FimdServer interface {
	CreateWatch(context.Context, *FimdConfig) (*FimdHandle, error)
	DestroyWatch(context.Context, *FimdConfig) (*Empty, error)
	GetWatchState(*Empty, Fimd_GetWatchStateServer) error
}

func RegisterFimdServer(s *grpc.Server, srv FimdServer) {
	s.RegisterService(&_Fimd_serviceDesc, srv)
}

func _Fimd_CreateWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FimdConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FimdServer).CreateWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fim.Fimd/CreateWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FimdServer).CreateWatch(ctx, req.(*FimdConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fimd_DestroyWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FimdConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FimdServer).DestroyWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fim.Fimd/DestroyWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FimdServer).DestroyWatch(ctx, req.(*FimdConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fimd_GetWatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FimdServer).GetWatchState(m, &fimdGetWatchStateServer{stream})
}

type Fimd_GetWatchStateServer interface {
	Send(*FimdHandle) error
	grpc.ServerStream
}

type fimdGetWatchStateServer struct {
	grpc.ServerStream
}

func (x *fimdGetWatchStateServer) Send(m *FimdHandle) error {
	return x.ServerStream.SendMsg(m)
}

var _Fimd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fim.Fimd",
	HandlerType: (*FimdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWatch",
			Handler:    _Fimd_CreateWatch_Handler,
		},
		{
			MethodName: "DestroyWatch",
			Handler:    _Fimd_DestroyWatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWatchState",
			Handler:       _Fimd_GetWatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fim.proto",
}

func init() { proto.RegisterFile("fim.proto", fileDescriptor_fim_56e8d7c6580709f8) }

var fileDescriptor_fim_56e8d7c6580709f8 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x8f, 0xd3, 0x3e,
	0x10, 0xdd, 0x34, 0x49, 0xbb, 0x99, 0xfd, 0xfd, 0xf8, 0x63, 0xa1, 0x95, 0x55, 0x71, 0x88, 0x72,
	0x40, 0xb9, 0x50, 0x95, 0x05, 0x09, 0xc4, 0x75, 0xdb, 0xc2, 0x89, 0x83, 0x17, 0x89, 0xb3, 0x37,
	0x99, 0xa6, 0x86, 0x3a, 0x0e, 0x8e, 0x5b, 0x91, 0x6f, 0xc1, 0x11, 0xf1, 0x41, 0xf8, 0x7c, 0xc8,
	0x93, 0xa6, 0x45, 0xb0, 0xdc, 0xb8, 0xcd, 0x7b, 0x33, 0xee, 0xcc, 0x7b, 0xaf, 0x81, 0x64, 0xad,
	0xf4, 0xac, 0xb1, 0xc6, 0x19, 0x16, 0xae, 0x95, 0xce, 0x7e, 0x04, 0x00, 0x2b, 0xa5, 0xcb, 0x6b,
	0x53, 0xaf, 0x55, 0xc5, 0xa6, 0x70, 0x5e, 0x9b, 0x12, 0xdf, 0x49, 0x8d, 0x3c, 0x48, 0x83, 0x3c,
	0x11, 0x47, 0xcc, 0x38, 0x4c, 0x1a, 0x53, 0x52, 0x6b, 0x44, 0xad, 0x01, 0xb2, 0x07, 0x10, 0x36,
	0xaa, 0xe4, 0x61, 0x1a, 0xe6, 0xb1, 0xf0, 0xa5, 0x67, 0x0a, 0x55, 0xf2, 0x28, 0x0d, 0xf3, 0x44,
	0xf8, 0x92, 0xcd, 0x61, 0xd2, 0xee, 0x6e, 0x3f, 0x62, 0xe1, 0x78, 0x9c, 0x86, 0xf9, 0xc5, 0xd5,
	0xe5, 0xcc, 0x9f, 0xb2, 0x52, 0xfa, 0x83, 0x74, 0xc5, 0x06, 0xed, 0x4d, 0xdf, 0x15, 0xc3, 0x18,
	0x7b, 0x0c, 0xc9, 0xd6, 0x54, 0x2b, 0x63, 0xb5, 0x74, 0x7c, 0x4c, 0x1b, 0x4f, 0x44, 0xf6, 0x6d,
	0x04, 0x0f, 0xff, 0x78, 0xcc, 0x18, 0x44, 0x8d, 0x74, 0x1b, 0x1e, 0xd0, 0x62, 0xaa, 0xd9, 0x23,
	0x88, 0x71, 0x8f, 0xb5, 0xe3, 0x23, 0x22, 0x7b, 0xc0, 0x2e, 0x61, 0xac, 0xaa, 0xda, 0x58, 0xa4,
	0xb3, 0x13, 0x71, 0x40, 0x5e, 0xa5, 0xa9, 0xb7, 0xdd, 0x42, 0x59, 0x1e, 0xa5, 0x41, 0x7e, 0x2e,
	0x06, 0xe8, 0xef, 0xb1, 0x58, 0xec, 0x6c, 0xab, 0xf6, 0xc8, 0x63, 0xea, 0x9d, 0x08, 0xef, 0x9c,
	0x96, 0x5f, 0x16, 0xd8, 0xb8, 0x0d, 0x1d, 0x1b, 0x8b, 0x23, 0x66, 0x2f, 0x20, 0x72, 0xb2, 0x6a,
	0xf9, 0x84, 0x84, 0xa7, 0x77, 0x0b, 0x9f, 0xbd, 0x97, 0x55, 0xbb, 0xac, 0x9d, 0xed, 0x04, 0x4d,
	0x4f, 0x5f, 0x42, 0x72, 0xa4, 0xbc, 0xa1, 0x9f, 0xb0, 0x3b, 0x64, 0xe2, 0x4b, 0x2f, 0x6b, 0x2f,
	0xb7, 0xbb, 0x21, 0x8c, 0x1e, 0xbc, 0x1e, 0xbd, 0x0a, 0xb2, 0xaf, 0x87, 0x4c, 0xdf, 0xca, 0xba,
	0xdc, 0xe2, 0x3f, 0xcb, 0xf4, 0x09, 0xdc, 0x6b, 0xac, 0x29, 0xb0, 0x6d, 0x97, 0xde, 0xc1, 0x75,
	0x1f, 0x6f, 0x2c, 0x7e, 0x63, 0x7d, 0x06, 0xfa, 0xf3, 0xaa, 0x24, 0x8b, 0x62, 0x41, 0x75, 0x36,
	0x81, 0x78, 0xa9, 0x1b, 0xd7, 0x5d, 0x7d, 0x0f, 0x20, 0xf2, 0xb7, 0xb1, 0x67, 0x70, 0x71, 0x6d,
	0x51, 0x3a, 0x24, 0x17, 0xd8, 0xfd, 0xc1, 0x94, 0xc3, 0x3f, 0x71, 0x7a, 0x22, 0x7a, 0x19, 0xd9,
	0x19, 0x7b, 0x0a, 0xff, 0x2d, 0xb0, 0x75, 0xd6, 0x74, 0x7f, 0x79, 0x03, 0x44, 0xd0, 0xa2, 0xec,
	0x8c, 0xcd, 0xe1, 0xff, 0x37, 0xe8, 0x68, 0xf4, 0xc6, 0x49, 0x87, 0xec, 0x97, 0xf6, 0x1d, 0x3f,
	0x3f, 0x0f, 0x6e, 0xc7, 0xf4, 0x61, 0x3c, 0xff, 0x19, 0x00, 0x00, 0xff, 0xff, 0x94, 0xdf, 0xa0,
	0x2b, 0x25, 0x03, 0x00, 0x00,
}
