// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fim.proto

#ifndef PROTOBUF_INCLUDED_fim_2eproto
#define PROTOBUF_INCLUDED_fim_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_fim_2eproto 

namespace protobuf_fim_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_fim_2eproto
namespace fim {
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class FimWatcherSubject;
class FimWatcherSubjectDefaultTypeInternal;
extern FimWatcherSubjectDefaultTypeInternal _FimWatcherSubject_default_instance_;
class FimWatcherSubject_TagsEntry_DoNotUse;
class FimWatcherSubject_TagsEntry_DoNotUseDefaultTypeInternal;
extern FimWatcherSubject_TagsEntry_DoNotUseDefaultTypeInternal _FimWatcherSubject_TagsEntry_DoNotUse_default_instance_;
class FimdConfig;
class FimdConfigDefaultTypeInternal;
extern FimdConfigDefaultTypeInternal _FimdConfig_default_instance_;
class FimdHandle;
class FimdHandleDefaultTypeInternal;
extern FimdHandleDefaultTypeInternal _FimdHandle_default_instance_;
class FimdMetricsHandle;
class FimdMetricsHandleDefaultTypeInternal;
extern FimdMetricsHandleDefaultTypeInternal _FimdMetricsHandle_default_instance_;
}  // namespace fim
namespace google {
namespace protobuf {
template<> ::fim::Empty* Arena::CreateMaybeMessage<::fim::Empty>(Arena*);
template<> ::fim::FimWatcherSubject* Arena::CreateMaybeMessage<::fim::FimWatcherSubject>(Arena*);
template<> ::fim::FimWatcherSubject_TagsEntry_DoNotUse* Arena::CreateMaybeMessage<::fim::FimWatcherSubject_TagsEntry_DoNotUse>(Arena*);
template<> ::fim::FimdConfig* Arena::CreateMaybeMessage<::fim::FimdConfig>(Arena*);
template<> ::fim::FimdHandle* Arena::CreateMaybeMessage<::fim::FimdHandle>(Arena*);
template<> ::fim::FimdMetricsHandle* Arena::CreateMaybeMessage<::fim::FimdMetricsHandle>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace fim {

// ===================================================================

class FimdConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fim.FimdConfig) */ {
 public:
  FimdConfig();
  virtual ~FimdConfig();

  FimdConfig(const FimdConfig& from);

  inline FimdConfig& operator=(const FimdConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FimdConfig(FimdConfig&& from) noexcept
    : FimdConfig() {
    *this = ::std::move(from);
  }

  inline FimdConfig& operator=(FimdConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FimdConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FimdConfig* internal_default_instance() {
    return reinterpret_cast<const FimdConfig*>(
               &_FimdConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FimdConfig* other);
  friend void swap(FimdConfig& a, FimdConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FimdConfig* New() const final {
    return CreateMaybeMessage<FimdConfig>(NULL);
  }

  FimdConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FimdConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FimdConfig& from);
  void MergeFrom(const FimdConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FimdConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 pid = 4;
  int pid_size() const;
  void clear_pid();
  static const int kPidFieldNumber = 4;
  ::google::protobuf::int32 pid(int index) const;
  void set_pid(int index, ::google::protobuf::int32 value);
  void add_pid(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      pid() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_pid();

  // repeated string cid = 5;
  int cid_size() const;
  void clear_cid();
  static const int kCidFieldNumber = 5;
  const ::std::string& cid(int index) const;
  ::std::string* mutable_cid(int index);
  void set_cid(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_cid(int index, ::std::string&& value);
  #endif
  void set_cid(int index, const char* value);
  void set_cid(int index, const char* value, size_t size);
  ::std::string* add_cid();
  void add_cid(const ::std::string& value);
  #if LANG_CXX11
  void add_cid(::std::string&& value);
  #endif
  void add_cid(const char* value);
  void add_cid(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& cid() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_cid();

  // repeated .fim.FimWatcherSubject subject = 6;
  int subject_size() const;
  void clear_subject();
  static const int kSubjectFieldNumber = 6;
  ::fim::FimWatcherSubject* mutable_subject(int index);
  ::google::protobuf::RepeatedPtrField< ::fim::FimWatcherSubject >*
      mutable_subject();
  const ::fim::FimWatcherSubject& subject(int index) const;
  ::fim::FimWatcherSubject* add_subject();
  const ::google::protobuf::RepeatedPtrField< ::fim::FimWatcherSubject >&
      subject() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string nodeName = 2;
  void clear_nodename();
  static const int kNodeNameFieldNumber = 2;
  const ::std::string& nodename() const;
  void set_nodename(const ::std::string& value);
  #if LANG_CXX11
  void set_nodename(::std::string&& value);
  #endif
  void set_nodename(const char* value);
  void set_nodename(const char* value, size_t size);
  ::std::string* mutable_nodename();
  ::std::string* release_nodename();
  void set_allocated_nodename(::std::string* nodename);

  // string podName = 3;
  void clear_podname();
  static const int kPodNameFieldNumber = 3;
  const ::std::string& podname() const;
  void set_podname(const ::std::string& value);
  #if LANG_CXX11
  void set_podname(::std::string&& value);
  #endif
  void set_podname(const char* value);
  void set_podname(const char* value, size_t size);
  ::std::string* mutable_podname();
  ::std::string* release_podname();
  void set_allocated_podname(::std::string* podname);

  // string logFormat = 7;
  void clear_logformat();
  static const int kLogFormatFieldNumber = 7;
  const ::std::string& logformat() const;
  void set_logformat(const ::std::string& value);
  #if LANG_CXX11
  void set_logformat(::std::string&& value);
  #endif
  void set_logformat(const char* value);
  void set_logformat(const char* value, size_t size);
  ::std::string* mutable_logformat();
  ::std::string* release_logformat();
  void set_allocated_logformat(::std::string* logformat);

  // @@protoc_insertion_point(class_scope:fim.FimdConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > pid_;
  mutable int _pid_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> cid_;
  ::google::protobuf::RepeatedPtrField< ::fim::FimWatcherSubject > subject_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr nodename_;
  ::google::protobuf::internal::ArenaStringPtr podname_;
  ::google::protobuf::internal::ArenaStringPtr logformat_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fim_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FimWatcherSubject_TagsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<FimWatcherSubject_TagsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<FimWatcherSubject_TagsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  FimWatcherSubject_TagsEntry_DoNotUse();
  FimWatcherSubject_TagsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const FimWatcherSubject_TagsEntry_DoNotUse& other);
  static const FimWatcherSubject_TagsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const FimWatcherSubject_TagsEntry_DoNotUse*>(&_FimWatcherSubject_TagsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class FimWatcherSubject : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fim.FimWatcherSubject) */ {
 public:
  FimWatcherSubject();
  virtual ~FimWatcherSubject();

  FimWatcherSubject(const FimWatcherSubject& from);

  inline FimWatcherSubject& operator=(const FimWatcherSubject& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FimWatcherSubject(FimWatcherSubject&& from) noexcept
    : FimWatcherSubject() {
    *this = ::std::move(from);
  }

  inline FimWatcherSubject& operator=(FimWatcherSubject&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FimWatcherSubject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FimWatcherSubject* internal_default_instance() {
    return reinterpret_cast<const FimWatcherSubject*>(
               &_FimWatcherSubject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(FimWatcherSubject* other);
  friend void swap(FimWatcherSubject& a, FimWatcherSubject& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FimWatcherSubject* New() const final {
    return CreateMaybeMessage<FimWatcherSubject>(NULL);
  }

  FimWatcherSubject* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FimWatcherSubject>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FimWatcherSubject& from);
  void MergeFrom(const FimWatcherSubject& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FimWatcherSubject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated string path = 1;
  int path_size() const;
  void clear_path();
  static const int kPathFieldNumber = 1;
  const ::std::string& path(int index) const;
  ::std::string* mutable_path(int index);
  void set_path(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_path(int index, ::std::string&& value);
  #endif
  void set_path(int index, const char* value);
  void set_path(int index, const char* value, size_t size);
  ::std::string* add_path();
  void add_path(const ::std::string& value);
  #if LANG_CXX11
  void add_path(::std::string&& value);
  #endif
  void add_path(const char* value);
  void add_path(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& path() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_path();

  // repeated string event = 2;
  int event_size() const;
  void clear_event();
  static const int kEventFieldNumber = 2;
  const ::std::string& event(int index) const;
  ::std::string* mutable_event(int index);
  void set_event(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_event(int index, ::std::string&& value);
  #endif
  void set_event(int index, const char* value);
  void set_event(int index, const char* value, size_t size);
  ::std::string* add_event();
  void add_event(const ::std::string& value);
  #if LANG_CXX11
  void add_event(::std::string&& value);
  #endif
  void add_event(const char* value);
  void add_event(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& event() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_event();

  // repeated string ignore = 3;
  int ignore_size() const;
  void clear_ignore();
  static const int kIgnoreFieldNumber = 3;
  const ::std::string& ignore(int index) const;
  ::std::string* mutable_ignore(int index);
  void set_ignore(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_ignore(int index, ::std::string&& value);
  #endif
  void set_ignore(int index, const char* value);
  void set_ignore(int index, const char* value, size_t size);
  ::std::string* add_ignore();
  void add_ignore(const ::std::string& value);
  #if LANG_CXX11
  void add_ignore(::std::string&& value);
  #endif
  void add_ignore(const char* value);
  void add_ignore(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& ignore() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_ignore();

  // map<string, string> tags = 7;
  int tags_size() const;
  void clear_tags();
  static const int kTagsFieldNumber = 7;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      tags() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_tags();

  // bool onlyDir = 4;
  void clear_onlydir();
  static const int kOnlyDirFieldNumber = 4;
  bool onlydir() const;
  void set_onlydir(bool value);

  // bool recursive = 5;
  void clear_recursive();
  static const int kRecursiveFieldNumber = 5;
  bool recursive() const;
  void set_recursive(bool value);

  // int32 maxDepth = 6;
  void clear_maxdepth();
  static const int kMaxDepthFieldNumber = 6;
  ::google::protobuf::int32 maxdepth() const;
  void set_maxdepth(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fim.FimWatcherSubject)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> path_;
  ::google::protobuf::RepeatedPtrField< ::std::string> event_;
  ::google::protobuf::RepeatedPtrField< ::std::string> ignore_;
  ::google::protobuf::internal::MapField<
      FimWatcherSubject_TagsEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > tags_;
  bool onlydir_;
  bool recursive_;
  ::google::protobuf::int32 maxdepth_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fim_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FimdHandle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fim.FimdHandle) */ {
 public:
  FimdHandle();
  virtual ~FimdHandle();

  FimdHandle(const FimdHandle& from);

  inline FimdHandle& operator=(const FimdHandle& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FimdHandle(FimdHandle&& from) noexcept
    : FimdHandle() {
    *this = ::std::move(from);
  }

  inline FimdHandle& operator=(FimdHandle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FimdHandle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FimdHandle* internal_default_instance() {
    return reinterpret_cast<const FimdHandle*>(
               &_FimdHandle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(FimdHandle* other);
  friend void swap(FimdHandle& a, FimdHandle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FimdHandle* New() const final {
    return CreateMaybeMessage<FimdHandle>(NULL);
  }

  FimdHandle* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FimdHandle>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FimdHandle& from);
  void MergeFrom(const FimdHandle& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FimdHandle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 pid = 3;
  int pid_size() const;
  void clear_pid();
  static const int kPidFieldNumber = 3;
  ::google::protobuf::int32 pid(int index) const;
  void set_pid(int index, ::google::protobuf::int32 value);
  void add_pid(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      pid() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_pid();

  // repeated int32 processEventfd = 4;
  int processeventfd_size() const;
  void clear_processeventfd();
  static const int kProcessEventfdFieldNumber = 4;
  ::google::protobuf::int32 processeventfd(int index) const;
  void set_processeventfd(int index, ::google::protobuf::int32 value);
  void add_processeventfd(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      processeventfd() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_processeventfd();

  // string nodeName = 1;
  void clear_nodename();
  static const int kNodeNameFieldNumber = 1;
  const ::std::string& nodename() const;
  void set_nodename(const ::std::string& value);
  #if LANG_CXX11
  void set_nodename(::std::string&& value);
  #endif
  void set_nodename(const char* value);
  void set_nodename(const char* value, size_t size);
  ::std::string* mutable_nodename();
  ::std::string* release_nodename();
  void set_allocated_nodename(::std::string* nodename);

  // string podName = 2;
  void clear_podname();
  static const int kPodNameFieldNumber = 2;
  const ::std::string& podname() const;
  void set_podname(const ::std::string& value);
  #if LANG_CXX11
  void set_podname(::std::string&& value);
  #endif
  void set_podname(const char* value);
  void set_podname(const char* value, size_t size);
  ::std::string* mutable_podname();
  ::std::string* release_podname();
  void set_allocated_podname(::std::string* podname);

  // int32 mqFd = 5;
  void clear_mqfd();
  static const int kMqFdFieldNumber = 5;
  ::google::protobuf::int32 mqfd() const;
  void set_mqfd(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fim.FimdHandle)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > pid_;
  mutable int _pid_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > processeventfd_;
  mutable int _processeventfd_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr nodename_;
  ::google::protobuf::internal::ArenaStringPtr podname_;
  ::google::protobuf::int32 mqfd_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fim_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FimdMetricsHandle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fim.FimdMetricsHandle) */ {
 public:
  FimdMetricsHandle();
  virtual ~FimdMetricsHandle();

  FimdMetricsHandle(const FimdMetricsHandle& from);

  inline FimdMetricsHandle& operator=(const FimdMetricsHandle& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FimdMetricsHandle(FimdMetricsHandle&& from) noexcept
    : FimdMetricsHandle() {
    *this = ::std::move(from);
  }

  inline FimdMetricsHandle& operator=(FimdMetricsHandle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FimdMetricsHandle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FimdMetricsHandle* internal_default_instance() {
    return reinterpret_cast<const FimdMetricsHandle*>(
               &_FimdMetricsHandle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(FimdMetricsHandle* other);
  friend void swap(FimdMetricsHandle& a, FimdMetricsHandle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FimdMetricsHandle* New() const final {
    return CreateMaybeMessage<FimdMetricsHandle>(NULL);
  }

  FimdMetricsHandle* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FimdMetricsHandle>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FimdMetricsHandle& from);
  void MergeFrom(const FimdMetricsHandle& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FimdMetricsHandle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string fimWatcher = 1;
  void clear_fimwatcher();
  static const int kFimWatcherFieldNumber = 1;
  const ::std::string& fimwatcher() const;
  void set_fimwatcher(const ::std::string& value);
  #if LANG_CXX11
  void set_fimwatcher(::std::string&& value);
  #endif
  void set_fimwatcher(const char* value);
  void set_fimwatcher(const char* value, size_t size);
  ::std::string* mutable_fimwatcher();
  ::std::string* release_fimwatcher();
  void set_allocated_fimwatcher(::std::string* fimwatcher);

  // string event = 2;
  void clear_event();
  static const int kEventFieldNumber = 2;
  const ::std::string& event() const;
  void set_event(const ::std::string& value);
  #if LANG_CXX11
  void set_event(::std::string&& value);
  #endif
  void set_event(const char* value);
  void set_event(const char* value, size_t size);
  ::std::string* mutable_event();
  ::std::string* release_event();
  void set_allocated_event(::std::string* event);

  // string nodeName = 3;
  void clear_nodename();
  static const int kNodeNameFieldNumber = 3;
  const ::std::string& nodename() const;
  void set_nodename(const ::std::string& value);
  #if LANG_CXX11
  void set_nodename(::std::string&& value);
  #endif
  void set_nodename(const char* value);
  void set_nodename(const char* value, size_t size);
  ::std::string* mutable_nodename();
  ::std::string* release_nodename();
  void set_allocated_nodename(::std::string* nodename);

  // @@protoc_insertion_point(class_scope:fim.FimdMetricsHandle)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr fimwatcher_;
  ::google::protobuf::internal::ArenaStringPtr event_;
  ::google::protobuf::internal::ArenaStringPtr nodename_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fim_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Empty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fim.Empty) */ {
 public:
  Empty();
  virtual ~Empty();

  Empty(const Empty& from);

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(Empty&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Empty& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Empty* other);
  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Empty* New() const final {
    return CreateMaybeMessage<Empty>(NULL);
  }

  Empty* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Empty& from);
  void MergeFrom(const Empty& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Empty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:fim.Empty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fim_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FimdConfig

// string name = 1;
inline void FimdConfig::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdConfig::name() const {
  // @@protoc_insertion_point(field_get:fim.FimdConfig.name)
  return name_.GetNoArena();
}
inline void FimdConfig::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdConfig.name)
}
#if LANG_CXX11
inline void FimdConfig::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdConfig.name)
}
#endif
inline void FimdConfig::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdConfig.name)
}
inline void FimdConfig::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdConfig.name)
}
inline ::std::string* FimdConfig::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdConfig.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdConfig::release_name() {
  // @@protoc_insertion_point(field_release:fim.FimdConfig.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdConfig::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdConfig.name)
}

// string nodeName = 2;
inline void FimdConfig::clear_nodename() {
  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdConfig::nodename() const {
  // @@protoc_insertion_point(field_get:fim.FimdConfig.nodeName)
  return nodename_.GetNoArena();
}
inline void FimdConfig::set_nodename(const ::std::string& value) {
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdConfig.nodeName)
}
#if LANG_CXX11
inline void FimdConfig::set_nodename(::std::string&& value) {
  
  nodename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdConfig.nodeName)
}
#endif
inline void FimdConfig::set_nodename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdConfig.nodeName)
}
inline void FimdConfig::set_nodename(const char* value, size_t size) {
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdConfig.nodeName)
}
inline ::std::string* FimdConfig::mutable_nodename() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdConfig.nodeName)
  return nodename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdConfig::release_nodename() {
  // @@protoc_insertion_point(field_release:fim.FimdConfig.nodeName)
  
  return nodename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdConfig::set_allocated_nodename(::std::string* nodename) {
  if (nodename != NULL) {
    
  } else {
    
  }
  nodename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nodename);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdConfig.nodeName)
}

// string podName = 3;
inline void FimdConfig::clear_podname() {
  podname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdConfig::podname() const {
  // @@protoc_insertion_point(field_get:fim.FimdConfig.podName)
  return podname_.GetNoArena();
}
inline void FimdConfig::set_podname(const ::std::string& value) {
  
  podname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdConfig.podName)
}
#if LANG_CXX11
inline void FimdConfig::set_podname(::std::string&& value) {
  
  podname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdConfig.podName)
}
#endif
inline void FimdConfig::set_podname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  podname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdConfig.podName)
}
inline void FimdConfig::set_podname(const char* value, size_t size) {
  
  podname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdConfig.podName)
}
inline ::std::string* FimdConfig::mutable_podname() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdConfig.podName)
  return podname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdConfig::release_podname() {
  // @@protoc_insertion_point(field_release:fim.FimdConfig.podName)
  
  return podname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdConfig::set_allocated_podname(::std::string* podname) {
  if (podname != NULL) {
    
  } else {
    
  }
  podname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), podname);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdConfig.podName)
}

// repeated int32 pid = 4;
inline int FimdConfig::pid_size() const {
  return pid_.size();
}
inline void FimdConfig::clear_pid() {
  pid_.Clear();
}
inline ::google::protobuf::int32 FimdConfig::pid(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimdConfig.pid)
  return pid_.Get(index);
}
inline void FimdConfig::set_pid(int index, ::google::protobuf::int32 value) {
  pid_.Set(index, value);
  // @@protoc_insertion_point(field_set:fim.FimdConfig.pid)
}
inline void FimdConfig::add_pid(::google::protobuf::int32 value) {
  pid_.Add(value);
  // @@protoc_insertion_point(field_add:fim.FimdConfig.pid)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
FimdConfig::pid() const {
  // @@protoc_insertion_point(field_list:fim.FimdConfig.pid)
  return pid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
FimdConfig::mutable_pid() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimdConfig.pid)
  return &pid_;
}

// repeated string cid = 5;
inline int FimdConfig::cid_size() const {
  return cid_.size();
}
inline void FimdConfig::clear_cid() {
  cid_.Clear();
}
inline const ::std::string& FimdConfig::cid(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimdConfig.cid)
  return cid_.Get(index);
}
inline ::std::string* FimdConfig::mutable_cid(int index) {
  // @@protoc_insertion_point(field_mutable:fim.FimdConfig.cid)
  return cid_.Mutable(index);
}
inline void FimdConfig::set_cid(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:fim.FimdConfig.cid)
  cid_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void FimdConfig::set_cid(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:fim.FimdConfig.cid)
  cid_.Mutable(index)->assign(std::move(value));
}
#endif
inline void FimdConfig::set_cid(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  cid_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fim.FimdConfig.cid)
}
inline void FimdConfig::set_cid(int index, const char* value, size_t size) {
  cid_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fim.FimdConfig.cid)
}
inline ::std::string* FimdConfig::add_cid() {
  // @@protoc_insertion_point(field_add_mutable:fim.FimdConfig.cid)
  return cid_.Add();
}
inline void FimdConfig::add_cid(const ::std::string& value) {
  cid_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fim.FimdConfig.cid)
}
#if LANG_CXX11
inline void FimdConfig::add_cid(::std::string&& value) {
  cid_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fim.FimdConfig.cid)
}
#endif
inline void FimdConfig::add_cid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  cid_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fim.FimdConfig.cid)
}
inline void FimdConfig::add_cid(const char* value, size_t size) {
  cid_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fim.FimdConfig.cid)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
FimdConfig::cid() const {
  // @@protoc_insertion_point(field_list:fim.FimdConfig.cid)
  return cid_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
FimdConfig::mutable_cid() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimdConfig.cid)
  return &cid_;
}

// repeated .fim.FimWatcherSubject subject = 6;
inline int FimdConfig::subject_size() const {
  return subject_.size();
}
inline void FimdConfig::clear_subject() {
  subject_.Clear();
}
inline ::fim::FimWatcherSubject* FimdConfig::mutable_subject(int index) {
  // @@protoc_insertion_point(field_mutable:fim.FimdConfig.subject)
  return subject_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::fim::FimWatcherSubject >*
FimdConfig::mutable_subject() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimdConfig.subject)
  return &subject_;
}
inline const ::fim::FimWatcherSubject& FimdConfig::subject(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimdConfig.subject)
  return subject_.Get(index);
}
inline ::fim::FimWatcherSubject* FimdConfig::add_subject() {
  // @@protoc_insertion_point(field_add:fim.FimdConfig.subject)
  return subject_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::fim::FimWatcherSubject >&
FimdConfig::subject() const {
  // @@protoc_insertion_point(field_list:fim.FimdConfig.subject)
  return subject_;
}

// string logFormat = 7;
inline void FimdConfig::clear_logformat() {
  logformat_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdConfig::logformat() const {
  // @@protoc_insertion_point(field_get:fim.FimdConfig.logFormat)
  return logformat_.GetNoArena();
}
inline void FimdConfig::set_logformat(const ::std::string& value) {
  
  logformat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdConfig.logFormat)
}
#if LANG_CXX11
inline void FimdConfig::set_logformat(::std::string&& value) {
  
  logformat_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdConfig.logFormat)
}
#endif
inline void FimdConfig::set_logformat(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  logformat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdConfig.logFormat)
}
inline void FimdConfig::set_logformat(const char* value, size_t size) {
  
  logformat_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdConfig.logFormat)
}
inline ::std::string* FimdConfig::mutable_logformat() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdConfig.logFormat)
  return logformat_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdConfig::release_logformat() {
  // @@protoc_insertion_point(field_release:fim.FimdConfig.logFormat)
  
  return logformat_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdConfig::set_allocated_logformat(::std::string* logformat) {
  if (logformat != NULL) {
    
  } else {
    
  }
  logformat_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), logformat);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdConfig.logFormat)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// FimWatcherSubject

// repeated string path = 1;
inline int FimWatcherSubject::path_size() const {
  return path_.size();
}
inline void FimWatcherSubject::clear_path() {
  path_.Clear();
}
inline const ::std::string& FimWatcherSubject::path(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimWatcherSubject.path)
  return path_.Get(index);
}
inline ::std::string* FimWatcherSubject::mutable_path(int index) {
  // @@protoc_insertion_point(field_mutable:fim.FimWatcherSubject.path)
  return path_.Mutable(index);
}
inline void FimWatcherSubject::set_path(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.path)
  path_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void FimWatcherSubject::set_path(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.path)
  path_.Mutable(index)->assign(std::move(value));
}
#endif
inline void FimWatcherSubject::set_path(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  path_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fim.FimWatcherSubject.path)
}
inline void FimWatcherSubject::set_path(int index, const char* value, size_t size) {
  path_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fim.FimWatcherSubject.path)
}
inline ::std::string* FimWatcherSubject::add_path() {
  // @@protoc_insertion_point(field_add_mutable:fim.FimWatcherSubject.path)
  return path_.Add();
}
inline void FimWatcherSubject::add_path(const ::std::string& value) {
  path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fim.FimWatcherSubject.path)
}
#if LANG_CXX11
inline void FimWatcherSubject::add_path(::std::string&& value) {
  path_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fim.FimWatcherSubject.path)
}
#endif
inline void FimWatcherSubject::add_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fim.FimWatcherSubject.path)
}
inline void FimWatcherSubject::add_path(const char* value, size_t size) {
  path_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fim.FimWatcherSubject.path)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
FimWatcherSubject::path() const {
  // @@protoc_insertion_point(field_list:fim.FimWatcherSubject.path)
  return path_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
FimWatcherSubject::mutable_path() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimWatcherSubject.path)
  return &path_;
}

// repeated string event = 2;
inline int FimWatcherSubject::event_size() const {
  return event_.size();
}
inline void FimWatcherSubject::clear_event() {
  event_.Clear();
}
inline const ::std::string& FimWatcherSubject::event(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimWatcherSubject.event)
  return event_.Get(index);
}
inline ::std::string* FimWatcherSubject::mutable_event(int index) {
  // @@protoc_insertion_point(field_mutable:fim.FimWatcherSubject.event)
  return event_.Mutable(index);
}
inline void FimWatcherSubject::set_event(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.event)
  event_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void FimWatcherSubject::set_event(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.event)
  event_.Mutable(index)->assign(std::move(value));
}
#endif
inline void FimWatcherSubject::set_event(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  event_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fim.FimWatcherSubject.event)
}
inline void FimWatcherSubject::set_event(int index, const char* value, size_t size) {
  event_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fim.FimWatcherSubject.event)
}
inline ::std::string* FimWatcherSubject::add_event() {
  // @@protoc_insertion_point(field_add_mutable:fim.FimWatcherSubject.event)
  return event_.Add();
}
inline void FimWatcherSubject::add_event(const ::std::string& value) {
  event_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fim.FimWatcherSubject.event)
}
#if LANG_CXX11
inline void FimWatcherSubject::add_event(::std::string&& value) {
  event_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fim.FimWatcherSubject.event)
}
#endif
inline void FimWatcherSubject::add_event(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  event_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fim.FimWatcherSubject.event)
}
inline void FimWatcherSubject::add_event(const char* value, size_t size) {
  event_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fim.FimWatcherSubject.event)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
FimWatcherSubject::event() const {
  // @@protoc_insertion_point(field_list:fim.FimWatcherSubject.event)
  return event_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
FimWatcherSubject::mutable_event() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimWatcherSubject.event)
  return &event_;
}

// repeated string ignore = 3;
inline int FimWatcherSubject::ignore_size() const {
  return ignore_.size();
}
inline void FimWatcherSubject::clear_ignore() {
  ignore_.Clear();
}
inline const ::std::string& FimWatcherSubject::ignore(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimWatcherSubject.ignore)
  return ignore_.Get(index);
}
inline ::std::string* FimWatcherSubject::mutable_ignore(int index) {
  // @@protoc_insertion_point(field_mutable:fim.FimWatcherSubject.ignore)
  return ignore_.Mutable(index);
}
inline void FimWatcherSubject::set_ignore(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.ignore)
  ignore_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void FimWatcherSubject::set_ignore(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.ignore)
  ignore_.Mutable(index)->assign(std::move(value));
}
#endif
inline void FimWatcherSubject::set_ignore(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  ignore_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fim.FimWatcherSubject.ignore)
}
inline void FimWatcherSubject::set_ignore(int index, const char* value, size_t size) {
  ignore_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fim.FimWatcherSubject.ignore)
}
inline ::std::string* FimWatcherSubject::add_ignore() {
  // @@protoc_insertion_point(field_add_mutable:fim.FimWatcherSubject.ignore)
  return ignore_.Add();
}
inline void FimWatcherSubject::add_ignore(const ::std::string& value) {
  ignore_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fim.FimWatcherSubject.ignore)
}
#if LANG_CXX11
inline void FimWatcherSubject::add_ignore(::std::string&& value) {
  ignore_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fim.FimWatcherSubject.ignore)
}
#endif
inline void FimWatcherSubject::add_ignore(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  ignore_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fim.FimWatcherSubject.ignore)
}
inline void FimWatcherSubject::add_ignore(const char* value, size_t size) {
  ignore_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fim.FimWatcherSubject.ignore)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
FimWatcherSubject::ignore() const {
  // @@protoc_insertion_point(field_list:fim.FimWatcherSubject.ignore)
  return ignore_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
FimWatcherSubject::mutable_ignore() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimWatcherSubject.ignore)
  return &ignore_;
}

// bool onlyDir = 4;
inline void FimWatcherSubject::clear_onlydir() {
  onlydir_ = false;
}
inline bool FimWatcherSubject::onlydir() const {
  // @@protoc_insertion_point(field_get:fim.FimWatcherSubject.onlyDir)
  return onlydir_;
}
inline void FimWatcherSubject::set_onlydir(bool value) {
  
  onlydir_ = value;
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.onlyDir)
}

// bool recursive = 5;
inline void FimWatcherSubject::clear_recursive() {
  recursive_ = false;
}
inline bool FimWatcherSubject::recursive() const {
  // @@protoc_insertion_point(field_get:fim.FimWatcherSubject.recursive)
  return recursive_;
}
inline void FimWatcherSubject::set_recursive(bool value) {
  
  recursive_ = value;
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.recursive)
}

// int32 maxDepth = 6;
inline void FimWatcherSubject::clear_maxdepth() {
  maxdepth_ = 0;
}
inline ::google::protobuf::int32 FimWatcherSubject::maxdepth() const {
  // @@protoc_insertion_point(field_get:fim.FimWatcherSubject.maxDepth)
  return maxdepth_;
}
inline void FimWatcherSubject::set_maxdepth(::google::protobuf::int32 value) {
  
  maxdepth_ = value;
  // @@protoc_insertion_point(field_set:fim.FimWatcherSubject.maxDepth)
}

// map<string, string> tags = 7;
inline int FimWatcherSubject::tags_size() const {
  return tags_.size();
}
inline void FimWatcherSubject::clear_tags() {
  tags_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
FimWatcherSubject::tags() const {
  // @@protoc_insertion_point(field_map:fim.FimWatcherSubject.tags)
  return tags_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
FimWatcherSubject::mutable_tags() {
  // @@protoc_insertion_point(field_mutable_map:fim.FimWatcherSubject.tags)
  return tags_.MutableMap();
}

// -------------------------------------------------------------------

// FimdHandle

// string nodeName = 1;
inline void FimdHandle::clear_nodename() {
  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdHandle::nodename() const {
  // @@protoc_insertion_point(field_get:fim.FimdHandle.nodeName)
  return nodename_.GetNoArena();
}
inline void FimdHandle::set_nodename(const ::std::string& value) {
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdHandle.nodeName)
}
#if LANG_CXX11
inline void FimdHandle::set_nodename(::std::string&& value) {
  
  nodename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdHandle.nodeName)
}
#endif
inline void FimdHandle::set_nodename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdHandle.nodeName)
}
inline void FimdHandle::set_nodename(const char* value, size_t size) {
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdHandle.nodeName)
}
inline ::std::string* FimdHandle::mutable_nodename() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdHandle.nodeName)
  return nodename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdHandle::release_nodename() {
  // @@protoc_insertion_point(field_release:fim.FimdHandle.nodeName)
  
  return nodename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdHandle::set_allocated_nodename(::std::string* nodename) {
  if (nodename != NULL) {
    
  } else {
    
  }
  nodename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nodename);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdHandle.nodeName)
}

// string podName = 2;
inline void FimdHandle::clear_podname() {
  podname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdHandle::podname() const {
  // @@protoc_insertion_point(field_get:fim.FimdHandle.podName)
  return podname_.GetNoArena();
}
inline void FimdHandle::set_podname(const ::std::string& value) {
  
  podname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdHandle.podName)
}
#if LANG_CXX11
inline void FimdHandle::set_podname(::std::string&& value) {
  
  podname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdHandle.podName)
}
#endif
inline void FimdHandle::set_podname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  podname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdHandle.podName)
}
inline void FimdHandle::set_podname(const char* value, size_t size) {
  
  podname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdHandle.podName)
}
inline ::std::string* FimdHandle::mutable_podname() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdHandle.podName)
  return podname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdHandle::release_podname() {
  // @@protoc_insertion_point(field_release:fim.FimdHandle.podName)
  
  return podname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdHandle::set_allocated_podname(::std::string* podname) {
  if (podname != NULL) {
    
  } else {
    
  }
  podname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), podname);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdHandle.podName)
}

// repeated int32 pid = 3;
inline int FimdHandle::pid_size() const {
  return pid_.size();
}
inline void FimdHandle::clear_pid() {
  pid_.Clear();
}
inline ::google::protobuf::int32 FimdHandle::pid(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimdHandle.pid)
  return pid_.Get(index);
}
inline void FimdHandle::set_pid(int index, ::google::protobuf::int32 value) {
  pid_.Set(index, value);
  // @@protoc_insertion_point(field_set:fim.FimdHandle.pid)
}
inline void FimdHandle::add_pid(::google::protobuf::int32 value) {
  pid_.Add(value);
  // @@protoc_insertion_point(field_add:fim.FimdHandle.pid)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
FimdHandle::pid() const {
  // @@protoc_insertion_point(field_list:fim.FimdHandle.pid)
  return pid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
FimdHandle::mutable_pid() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimdHandle.pid)
  return &pid_;
}

// repeated int32 processEventfd = 4;
inline int FimdHandle::processeventfd_size() const {
  return processeventfd_.size();
}
inline void FimdHandle::clear_processeventfd() {
  processeventfd_.Clear();
}
inline ::google::protobuf::int32 FimdHandle::processeventfd(int index) const {
  // @@protoc_insertion_point(field_get:fim.FimdHandle.processEventfd)
  return processeventfd_.Get(index);
}
inline void FimdHandle::set_processeventfd(int index, ::google::protobuf::int32 value) {
  processeventfd_.Set(index, value);
  // @@protoc_insertion_point(field_set:fim.FimdHandle.processEventfd)
}
inline void FimdHandle::add_processeventfd(::google::protobuf::int32 value) {
  processeventfd_.Add(value);
  // @@protoc_insertion_point(field_add:fim.FimdHandle.processEventfd)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
FimdHandle::processeventfd() const {
  // @@protoc_insertion_point(field_list:fim.FimdHandle.processEventfd)
  return processeventfd_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
FimdHandle::mutable_processeventfd() {
  // @@protoc_insertion_point(field_mutable_list:fim.FimdHandle.processEventfd)
  return &processeventfd_;
}

// int32 mqFd = 5;
inline void FimdHandle::clear_mqfd() {
  mqfd_ = 0;
}
inline ::google::protobuf::int32 FimdHandle::mqfd() const {
  // @@protoc_insertion_point(field_get:fim.FimdHandle.mqFd)
  return mqfd_;
}
inline void FimdHandle::set_mqfd(::google::protobuf::int32 value) {
  
  mqfd_ = value;
  // @@protoc_insertion_point(field_set:fim.FimdHandle.mqFd)
}

// -------------------------------------------------------------------

// FimdMetricsHandle

// string fimWatcher = 1;
inline void FimdMetricsHandle::clear_fimwatcher() {
  fimwatcher_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdMetricsHandle::fimwatcher() const {
  // @@protoc_insertion_point(field_get:fim.FimdMetricsHandle.fimWatcher)
  return fimwatcher_.GetNoArena();
}
inline void FimdMetricsHandle::set_fimwatcher(const ::std::string& value) {
  
  fimwatcher_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdMetricsHandle.fimWatcher)
}
#if LANG_CXX11
inline void FimdMetricsHandle::set_fimwatcher(::std::string&& value) {
  
  fimwatcher_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdMetricsHandle.fimWatcher)
}
#endif
inline void FimdMetricsHandle::set_fimwatcher(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  fimwatcher_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdMetricsHandle.fimWatcher)
}
inline void FimdMetricsHandle::set_fimwatcher(const char* value, size_t size) {
  
  fimwatcher_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdMetricsHandle.fimWatcher)
}
inline ::std::string* FimdMetricsHandle::mutable_fimwatcher() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdMetricsHandle.fimWatcher)
  return fimwatcher_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdMetricsHandle::release_fimwatcher() {
  // @@protoc_insertion_point(field_release:fim.FimdMetricsHandle.fimWatcher)
  
  return fimwatcher_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdMetricsHandle::set_allocated_fimwatcher(::std::string* fimwatcher) {
  if (fimwatcher != NULL) {
    
  } else {
    
  }
  fimwatcher_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fimwatcher);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdMetricsHandle.fimWatcher)
}

// string event = 2;
inline void FimdMetricsHandle::clear_event() {
  event_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdMetricsHandle::event() const {
  // @@protoc_insertion_point(field_get:fim.FimdMetricsHandle.event)
  return event_.GetNoArena();
}
inline void FimdMetricsHandle::set_event(const ::std::string& value) {
  
  event_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdMetricsHandle.event)
}
#if LANG_CXX11
inline void FimdMetricsHandle::set_event(::std::string&& value) {
  
  event_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdMetricsHandle.event)
}
#endif
inline void FimdMetricsHandle::set_event(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  event_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdMetricsHandle.event)
}
inline void FimdMetricsHandle::set_event(const char* value, size_t size) {
  
  event_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdMetricsHandle.event)
}
inline ::std::string* FimdMetricsHandle::mutable_event() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdMetricsHandle.event)
  return event_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdMetricsHandle::release_event() {
  // @@protoc_insertion_point(field_release:fim.FimdMetricsHandle.event)
  
  return event_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdMetricsHandle::set_allocated_event(::std::string* event) {
  if (event != NULL) {
    
  } else {
    
  }
  event_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), event);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdMetricsHandle.event)
}

// string nodeName = 3;
inline void FimdMetricsHandle::clear_nodename() {
  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FimdMetricsHandle::nodename() const {
  // @@protoc_insertion_point(field_get:fim.FimdMetricsHandle.nodeName)
  return nodename_.GetNoArena();
}
inline void FimdMetricsHandle::set_nodename(const ::std::string& value) {
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fim.FimdMetricsHandle.nodeName)
}
#if LANG_CXX11
inline void FimdMetricsHandle::set_nodename(::std::string&& value) {
  
  nodename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fim.FimdMetricsHandle.nodeName)
}
#endif
inline void FimdMetricsHandle::set_nodename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fim.FimdMetricsHandle.nodeName)
}
inline void FimdMetricsHandle::set_nodename(const char* value, size_t size) {
  
  nodename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fim.FimdMetricsHandle.nodeName)
}
inline ::std::string* FimdMetricsHandle::mutable_nodename() {
  
  // @@protoc_insertion_point(field_mutable:fim.FimdMetricsHandle.nodeName)
  return nodename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FimdMetricsHandle::release_nodename() {
  // @@protoc_insertion_point(field_release:fim.FimdMetricsHandle.nodeName)
  
  return nodename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FimdMetricsHandle::set_allocated_nodename(::std::string* nodename) {
  if (nodename != NULL) {
    
  } else {
    
  }
  nodename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nodename);
  // @@protoc_insertion_point(field_set_allocated:fim.FimdMetricsHandle.nodeName)
}

// -------------------------------------------------------------------

// Empty

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fim

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_fim_2eproto
